


services:

  lab:
    build:
      context: ./lab
      dockerfile: Dockerfile
    image: postgers-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r5t
      POSTGRES_USER: yan
      POSTGRES_DB: krya
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080